spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:8080/realms/microservices-claim/protocol/openid-connect/token/introspect
          client-id: a6e35f97-03c2-4d79-b177-f331fc7963b3
          client-secret: abYpqJBKwmfRKJ5N3QoCTA5UPGKYrK2D
  application:
    name: INVENTORY_SERVICE
  datasource:
    url: jdbc:h2:file:C:\Users\somav\Downloads\Microservices\DB\inventoryservice\inventory
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8082