spring:
  application:
    name: PRODUCT_SERVICE
  datasource:
    url: jdbc:h2:file:C:\Users\somav\Downloads\Microservices\DB\productservice\product
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8090